public class Foo {
    public String field ;
    public void test1( String val1){

      String oa = '1';

        String  val2 = fin( oa );
         val2 = 'okay';
        String field1 = val1;

        Id v = 1 ;
		String qry = 'SELECT Id FROM Account WHERE Id =';
		qry += v +  field1;
		Database.query(qry);


	}

	public void fun1( String o1){

	  rand( o1 );
	}
	public void rand( String o ) {

        test1( o );
	     fin() ;

	}
    public String getFrom(){
     return okax();
    }
	public String fin(int oa) {
       String val = getFrom();
	   return val  ;

	}
	public String fin(String okay ) {

    	   return 'okay' ;

    	}
	public String fin1() {

	   return 'okay' ;

	}


}